# Build settings
encoding: utf-8
name: Georgina M Personal Website
description: Personal website of Georgina M
url: http://gemcfadyen.github.io/georginam.com/
baseurl: /georginam.com
#markdown: redcarpet
linkedin: "https://uk.linkedin.com/in/georgina-mcfadyen-03942b104"
twitter: "https://twitter.com/gemcfadyen"
github_url: "https://github.com/gemcfadyen"
safe: true
lsi: false
github: [Repository metadata]
