# Build settings
encoding: utf-8
name: Personal Website
markdown: redcarpet
baseurl: /georginam.com
twitter_username: gemcfadyen
github_username:  gemcfadyen
safe: true
lsi: false
github: [Repository metadata]
